export const LIST_MY_POSTS_REQUEST = 'LIST_MY_POSTS_REQUEST';
export const LIST_MY_POSTS_SUCCESS = 'LIST_MY_POSTS_SUCCESS';
export const LIST_MY_POSTS_FAIL = 'LIST_MY_POSTS_FAIL';

export const LIST_LATEST_POSTS_REQUEST = 'LIST_LATEST_POSTS_REQUEST';
export const LIST_LATEST_POSTS_SUCCESS = 'LIST_LATEST_POSTS_SUCCESS';
export const LIST_LATEST_POSTS_FAIL = 'LIST_LATEST_POSTS_FAIL';

export const LIST_POST_BY_ID_REQUEST = 'LIST_POST_BY_ID_REQUEST';
export const LIST_POST_BY_ID_SUCCESS = 'LIST_POST_BY_ID_SUCCESS';
export const LIST_POST_BY_ID_FAIL = 'LIST_POST_BY_ID_FAIL';

export const LIST_USER_POSTS_REQUEST = 'LIST_USER_POSTS_REQUEST';
export const LIST_USER_POSTS_SUCCESS = 'LIST_USER_POSTS_SUCCESS';
export const LIST_USER_POSTS_FAIL = 'LIST_USER_POSTS_FAIL';

export const CREATE_POST_REQUEST = 'CREATE_POST_REQUEST';
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS';
export const CREATE_POST_FAIL = 'CREATE_POST_FAIL';

export const UPDATE_POST_REQUEST = 'UPDATE_POST_REQUEST';
export const UPDATE_POST_SUCCESS = 'UPDATE_POST_SUCCESS';
export const UPDATE_POST_FAIL = 'UPDATE_POST_FAIL';

export const DELETE_POST_REQUEST = 'DELETE_POST_REQUEST';
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';
export const DELETE_POST_FAIL = 'DELETE_POST_FAIL';

export const LIST_SEARCH_POSTS_REQUEST = 'LIST_SEARCH_POSTS_REQUEST';
export const LIST_SEARCH_POSTS_SUCCESS = 'LIST_SEARCH_POSTS_SUCCESS';
export const LIST_SEARCH_POSTS_FAIL = 'LIST_SEARCH_POSTS_FAIL';
